env:
  global:
    - QUIET=0
    - UML_FIG=0
    - UML_DOCKERCOMPOSE=1
  matrix:
    - BRANCH=v1.0.0
    - BRANCH=stable
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=aufs
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=devicemapper
#   - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=btrfs
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=vfs
#   - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=overlay
#   - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=aufs
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=devicemapper
#   - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=btrfs
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=vfs
#   - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=overlay

sudo: true

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - df -h
  - ./run docker info
  - ./run docker run busybox date
  - ./run docker-compose build
  - ./run docker-compose run aaa date
  - ./run docker info
  - df -h
